services:
- type: web
  name: conversor-online
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
  preBuildCommand: |
    apt-get update
    apt-get install -y poppler-utils ffmpeg libjpeg-dev